# FROM ubuntu:20.04
FROM ubuntu:18.04

# Install dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential \
    gcc-multilib

# Change example to the name of your challenge.
# Set up the user
ENV USER rings_of_saturn
WORKDIR /home/$USER
RUN useradd $USER

# Add source files
COPY ./src/libc6_2.27-3ubuntu1.2_amd64.deb /tmp
RUN dpkg -i /tmp/libc6_2.27-3ubuntu1.2_amd64.deb
COPY ./src/$USER.c /home/$USER/
COPY ./src/hexdump.c /home/$USER/
COPY ./src/hexdump.h /home/$USER/
COPY ./src/Makefile /home/$USER/Makefile

# Copy the binary AND any libraries it depends on
# into the build output directory
RUN mkdir /home/$USER/build
RUN make -C /home/$USER/ && \
    make -C /home/$USER/ debug && \
    ls /home/$USER/ && \
    cp /home/$USER/$USER /home/$USER/build/ && \
    cp /home/$USER/rings_of_saturn_dbg /home/$USER/build/ && \
    sh -c "ldd /home/$USER/build/$USER | grep '=>' | cut -d' ' -f3 | xargs -I '{}' cp -L -v '{}' /home/$USER/build/"

RUN chown -R root:$USER /home/$USER
RUN chmod -R 550 /home/$USER

CMD sleep 5